### ISSUE TITLE
RPW won't close

### ISSUE THREAD

**Issue by xman877** [MightyPork/rpw#94] opened 2016-10-29 16:59 UTC
Please follow those steps and check all the boxes `[x]` before submitting:
- [x] I can reproduce the issue. _If you can't, then we likely can't either._
- [x] My RPW is up to date.
- [x] I have checked that this issue isn't reported already.
- [x] My issue is not a question. Please post your questions to Gitter, or tweet at @MightyPork.
- [x] I have included all relevant information (crash log, Java/RPW/Minecraft/Windows version...)

Thank you!

_You can delete this "questionaire" if all boxes are checked - it's here 
to make sure people give some thought to their bug reports._

---

**What happened?**
I was trying to put some textures from another texture pack. When it was finish my RPW on Windows froze/crash and i cant get it off of my screen.I tried closing it but it it was frozen and i couldn't hit the close button. And I tried deleting it but it couldn't because it is open.
...

**Steps to reproduce:**
1. Take a resource pack to import into RPW Windows
2. While its importing, close the import log.

...

**Crash report (if any)**
It possibly crashed while importing. Im not sure if it either crashed because of the import or it crash when i closed it.
...

**Comment by Takoyaki1** [comment] 2016-12-31 00:19
I can't seem to reproduce the issue, mainly because you can't actually close the import dialogue without using task manager or similar apps. If I close the main RPW window, it remains open and gives me a crash report, and continues to import.

**Comment by AKTheKnight** [comment] 2017-03-16 21:50
Hey, If you're still having this issue then feel free to reopen the issue. I was unable to reproduce this so I am closing it for now

**Closed by AKTheKnight** 2017-03-16 21:50 UTC
