### ISSUE TITLE
Torch and other blocks are purple and black

### ISSUE THREAD

**Issue by CrossCreep** [MightyPork/rpw#93] opened 2016-10-23 11:42 UTC
Please follow those steps and check all the boxes `[x]` before submitting:
- [x] I can reproduce the issue. _If you can't, then we likely can't either._
- [x] My RPW is up to date.
- [x] I have checked that this issue isn't reported already.
- [x] My issue is not a question. Please post your questions to Gitter, or tweet at @MightyPork.
- [x] I have included all relevant information (crash log, Java/RPW/Minecraft/Windows version...)

Thank you!

_You can delete this "questionaire" if all boxes are checked - it's here 
to make sure people give some thought to their bug reports._

---

**What happened?**
I made my own texture pack but when i finished the torch or the Glowstone are black and purple. I tried all but one of them are always so. I used Sphax PureBDcraft. Its the newst version of RPW. The Pack is for 1.8.8.
- 

...

**Steps to reproduce:**

...

**Crash report (if any)**

...

**Comment by AKTheKnight** [comment] 2017-03-16 21:50
Hey, If you're still having this issue then feel free to reopen the issue. I was unable to reproduce this so I am closing it for now

**Closed by AKTheKnight** 2017-03-16 21:50 UTC
