### ISSUE TITLE
Sound Wizard - "Drag to Selected Files" not working

### ISSUE THREAD

**Issue by robosheep95** [MightyPork/rpw#50] opened 2015-06-21 03:30 UTC
![capture](https://cloud.githubusercontent.com/assets/12039757/8270242/edb2daae-179b-11e5-8ddd-050e866cc9c6.PNG)

I try to drag "hero" and I get the drag icon but it does not move.

**Comment by MightyPork** [comment] 2015-06-21 09:04
Duplicate of #47

**Closed by MightyPork** 2015-06-21 09:04 UTC
