### ISSUE TITLE
I can't find iron nugs

### ISSUE THREAD

**Issue by Alexdil** [MightyPork/rpw#100] opened 2017-02-05 17:37 UTC
**What happened?**
I can't find iron nugs
...

**Steps to reproduce:**
Look for iron nugs
...

**Crash report (if any)**
none
...

**Comment by AKTheKnight** [comment] 2017-03-16 21:50
Hey, If you're still having this issue then feel free to reopen the issue. I was unable to reproduce this so I am closing it for now

**Closed by AKTheKnight** 2017-03-16 21:50 UTC

**Comment by Alexdil** [comment] 2017-03-24 21:23
If you can't reproduce it then can you tell me where it is then? It's not under minerals like you'd think.

**Comment by MightyPork** [comment] 2017-03-24 21:55
I haven't checked, but some hints - there is a search function in the tree - think it's invoked by ctrl+F. And the Fancy Tree mode sometimes doesn't show items that were added to Minecraft after the last update - the tree categories are hard-coded in an INI file bundled in RPW. In particular, "iron nugs" are new - they can be in some other category: the matching is done using wildcards, they might've wound up pretty much anywhere
