### ISSUE TITLE
Mixed slashes in sounds.json

### ISSUE THREAD

**Issue by PvtPirate** [MightyPork/rpw#33] opened 2015-04-27 11:24 UTC
i created a pack with some custom sounds and i recently found this in the MC log:
[13:14:03] [Sound Library Loader/INFO]: Starting up SoundSystem...
[13:14:04] [Client thread/WARN]: File minecraft:sounds/records\13.ogg does not exist, cannot add it to event minecraft:records.13
[13:14:04] [Client thread/WARN]: File minecraft:sounds/records\cat.ogg does not exist, cannot add it to event minecraft:records.cat
[13:14:04] [Client thread/WARN]: File minecraft:sounds/mob\villager\janjansen03.ogg does not exist, cannot add it to event minecraft:mob.villager.idle
[13:14:04] [Client thread/WARN]: File minecraft:sounds/mob\villager\janjansen08.ogg does not exist, cannot add it to event minecraft:mob.villager.idle
[13:14:04] [Client thread/WARN]: File minecraft:sounds/mob\villager\janjansen09.ogg does not exist, cannot add it to event minecraft:mob.villager.idle
[13:14:04] [Client thread/WARN]: File minecraft:sounds/mob\villager\janjansen16.ogg does not exist, cannot add it to event minecraft:mob.villager.idle
[13:14:04] [Client thread/WARN]: File minecraft:sounds/mob\villager\janjansen17.ogg does not exist, cannot add it to event minecraft:mob.villager.idle
[13:14:04] [Client thread/WARN]: File minecraft:sounds/mob\villager\janjansen18.ogg does not exist, cannot add it to event minecraft:mob.villager.idle
[13:14:04] [Client thread/WARN]: File minecraft:sounds/mob\villager\janjansen23.ogg does not exist, cannot add it to event minecraft:mob.villager.idle
[13:14:04] [Client thread/WARN]: File minecraft:sounds/mob\villager\janjansen26.ogg does not exist, cannot add it to event minecraft:mob.villager.idle
[13:14:04] [Client thread/WARN]: File minecraft:sounds/mob\villager\janjansen33.ogg does not exist, cannot add it to event minecraft:mob.villager.idle
[13:14:04] [Client thread/WARN]: File minecraft:sounds/mob\villager\janjansen54.ogg does not exist, cannot add it to event minecraft:mob.villager.idle
[13:14:04] [Client thread/WARN]: File minecraft:sounds/mob\villager\janjansen58.ogg does not exist, cannot add it to event minecraft:mob.villager.idle
[13:14:04] [Client thread/WARN]: File minecraft:sounds/mob\villager\janjansen73.ogg does not exist, cannot add it to event minecraft:mob.villager.idle
[13:14:04] [Client thread/WARN]: File minecraft:sounds/mob\villager\haggle1.ogg does not exist, cannot add it to event minecraft:mob.villager.haggle
[13:14:04] [Client thread/WARN]: File minecraft:sounds/mob\villager\haggle2.ogg does not exist, cannot add it to event minecraft:mob.villager.haggle
[13:14:04] [Client thread/WARN]: File minecraft:sounds/mob\villager\haggle3.ogg does not exist, cannot add it to event minecraft:mob.villager.haggle

maybe it is because i created it with an old version of RPW - i seriously don't know which version i used when creating the pack, so maybe it is already solved in 3.9.2.
what confused me most was that both / and \ appear in the log's filepath.
i hope recreating the pack will solve the problem.

**Comment by MightyPork** [comment] 2015-04-27 11:37
Hi, to be honest, I have never tested RPW on Windows, it's built and tested only on Linux and mac, so that may be where the bad slashes are coming from.

Last change in the sound editor thing was in January, so if you have newer version than that, then it's likely still not fixed.

One thing to try, extract the pack zip, find sounds.json and correct the slashes (I believe forward slashes are the right ones).

Then put the whole thing into the resourcepacks/ MC folder (eg. `resourcepacks/mypack/`), it should work that way too, and try to select it in MC.

If it works, we know it's really the slashes causing havoc.

Also it'll be useful if you could put the pack somewhere so I can download and inspect it, I could find something. Maybe just the sounds.json file will be enough.

**Comment by PvtPirate** [comment] 2015-04-27 12:02
i constantly updated the RPW, but also constantly made new changes, but i don't know when i made them, so it could be from an older version.
can you recommend a good editor for opening the .json files, because the standard txt-editor doesnt sort the items, so it is very difficult to see the filestructure (i'm used to html and javascript syntax).
also i just saw my typo in the topic title.
I'll see what i can find out.

**Comment by MightyPork** [comment] 2015-04-27 12:20
it's just a text file, but with unix newlines, so that's why notepad messes it up. Notepad++ or Sublime Text, anything works OK.

Ok, try replacing the backslashes with forward slashes, that should do the trick. This should be easy to fix if you find that it's really the cause.

**Comment by PvtPirate** [comment] 2015-04-27 12:49
changing the \\ to // didnt change a thing, but making them single / got rid of the error.

**Comment by MightyPork** [comment] 2015-05-03 19:07
Here's a 3.9.3 prerelease, if you can please try whether the slashes problem is fixed by it.

https://dl.dropboxusercontent.com/u/64454818/TMP/RPW_393-pre1.jar

**Comment by MightyPork** [comment] 2015-05-14 10:47
Closed for lack of feedback, it's maybe fixed

**Closed by MightyPork** 2015-05-14 10:47 UTC
Labels: bug, waiting for reply
