### ISSUE TITLE
Vanilla Textures instead of imported ResourcePack

### ISSUE THREAD

**Issue by NightWolf4Ever** [MightyPork/rpw#89] opened 2016-07-03 12:53 UTC
**What happened?**
After importing a RPack, a lot of the assets used are from vanilla MC.(Found no way to get the RPack's files instead)
...

**Steps to reproduce:**
none
just happened.
...

**Comment by AKTheKnight** [comment] 2017-03-16 21:50
Hey, If you're still having this issue then feel free to reopen the issue. I was unable to reproduce this so I am closing it for now

**Closed by AKTheKnight** 2017-03-16 21:50 UTC
