### ISSUE TITLE
Why do OGG files not work?

### ISSUE THREAD

**Issue by Evan13698** [MightyPork/rpw#38] opened 2015-05-22 08:15 UTC
I want to add audio to the resource pack I am making except it looks like it only lets you add .ogg files. I saved in audacity (the program I am using to make audio) the file as a compressed .ogg file but when I added it to replace a music disc sound it didn't work and just played the normal music. Is there just something I am doing wrong or maybe can it accept other file types?

**Comment by MightyPork** [comment] 2015-05-22 08:24
I just tried it, replaced the disk 13 with Nightwish's "Nemo" track converted in Audacity to Ogg Vorbis, and it plays as expected. So I'm not sure where's the problem.

It's not possible to allow other types than Ogg Vorbis, that's a limitation of Minecraft itself.

**Comment by Evan13698** [comment] 2015-05-22 08:26
Oh... sry for reporting that. I think I saved my project as an .ogg file. Not the audio itself. :-( I messed up.

**Comment by MightyPork** [comment] 2015-05-22 08:26
it's okay, lemme know if you get it working

**Comment by Evan13698** [comment] 2015-05-22 08:27
Thx :-)

**Comment by Evan13698** [comment] 2015-05-22 08:34
Ok... still not working. Any suggestions on what I should do? Maybe replace an actual sound? Rather then music disc music?

**Comment by MightyPork** [comment] 2015-05-22 08:36
idk. If you can send me the output zip, I'll look if there's something wrong w/ it.

**Comment by Evan13698** [comment] 2015-05-22 08:38
U mean the file or the texture pack?

**Comment by MightyPork** [comment] 2015-05-22 08:42
the exported pack

**Comment by Evan13698** [comment] 2015-05-22 08:46
Sent an email with the pack

**Comment by MightyPork** [comment] 2015-05-22 08:49
didn't get it yet ._.

**Comment by Evan13698** [comment] 2015-05-22 08:51
Arghh! Why isn't it working

**Comment by Evan13698** [comment] 2015-05-22 08:51
Here it is resent

**Comment by Evan13698** [comment] 2015-05-22 08:54
Resent

**Comment by MightyPork** [comment] 2015-05-22 08:56
Didn't receive a thing. Do you have the correct mail ondra@ondrovo.com?

Maybe try put it on Dropbox or mediafire or something and delete after I get it

**Comment by MightyPork** [comment] 2015-05-22 09:00
good, got it

**Comment by Evan13698** [comment] 2015-05-22 09:01
Phew

**Comment by MightyPork** [comment] 2015-05-22 09:08
let's solve this on hangouts if you can, it'll be more complicated.

**Comment by Evan13698** [comment] 2015-05-22 09:09
Ok so what hangouts?

**Comment by MightyPork** [comment] 2015-05-22 09:10
i sent you a message there, you should see something like "want to accept hangout from ..." in gmail

**Comment by Evan13698** [comment] 2015-05-22 09:11
Nope don’t see anything like that

**Comment by MightyPork** [comment] 2015-05-22 09:12
odd, maybe you aren't "logged into hangouts", it should be on the right side. (or we can try skype chat.. just need some sort of chat for this. I need to work out how you got the zip you sent me)

**Comment by Evan13698** [comment] 2015-05-22 09:15
Ahh I have no idea how to get onto hangouts so why don’t we keep talking like this

Just tell me what you want to know

**Comment by MightyPork** [comment] 2015-05-22 09:17
alright, but this will be slow and I wanted to solve it quickly :P

basically what you sent me is not a valid resource pack, I don't believe it's what you got straight from RPW. There's .DS_Store bullshit files in it, and the root folder should directly contain the icon and mcmeta file, not a folder.

Also, the sounds are placed in a completely wrong place in the pack, which was fixed in January.

Do you have the latest RPW version? (4.0.0)

**Comment by MightyPork** [comment] 2015-05-22 09:18
btw 
![screenshot_2015-05-22_11-18-38](https://cloud.githubusercontent.com/assets/2041118/7767614/53a57d74-0074-11e5-973d-2c1082dfa092.png)

**Comment by Evan13698** [comment] 2015-05-22 09:22
Arghhh! I have no idea where hangouts is! Why Gmail!

**Comment by Evan13698** [comment] 2015-05-22 09:24
I sent a chat invite is that it?

**Comment by MightyPork** [comment] 2015-05-22 09:28
idk I got nothing. Let's try Gitter, you should get an invite in a sec (-> https://gitter.im/MightyPork/rpw_38)

**Comment by Evan13698** [comment] 2015-05-22 09:28
Got the invite I am on glitter

**Comment by Evan13698** [comment] 2015-05-22 09:47
Still not working :-( Will retry tomorrow otherwise rediscuss it

**Comment by Evan13698** [comment] 2015-05-24 06:23
Not working maybe rediscuss it tomorrow

**Comment by Jiggy-12321** [comment] 2015-05-25 21:21
I was able to reproduce it, although it requires deliberate mistakes to be made. I'm not sure exactly how you made all the mistakes required to duplicate this issue.

**Comment by Evan13698** [comment] 2015-05-25 21:36
Oh... Thats strange. Could you maybe use my audio to put the audio in as a
music disc music and working?  And send that back to me? I am happy to
reput in the textures.

**Comment by Jiggy-12321** [comment] 2015-05-25 21:37
Yeah. Send me the audio.

**Comment by Jiggy-12321** [comment] 2015-05-25 21:38
epicpcgamer81@gmail.com

**Comment by Evan13698** [comment] 2015-05-25 21:38
Ok turning on my computer

**Comment by Jiggy-12321** [comment] 2015-05-25 21:47
Maybe that it is too big or long?

**Comment by Evan13698** [comment] 2015-05-26 06:22
Naaa I have seen longer files work

**Comment by MightyPork** [comment] 2015-05-26 06:28
@Jiggy-12321 any luck reproducing this? because it still works ok for me

**Comment by Evan13698** [comment] 2015-05-26 06:29
Well could someone please send me a working one?

**Comment by MightyPork** [comment] 2015-05-26 06:32
well I don't have your file... send it and I'll try to

**Comment by Evan13698** [comment] 2015-05-26 06:33
Ok

**Comment by Evan13698** [comment] 2015-05-26 06:52
Retry

**Comment by MightyPork** [comment] 2015-05-26 06:58
this ain't gonna work, github removes attachments

**Comment by Evan13698** [comment] 2015-05-26 06:59
just view it on gmail

**Comment by MightyPork** [comment] 2015-05-26 07:00
![screenshot_2015-05-26_08-59-49](https://cloud.githubusercontent.com/assets/2041118/7806816/a0d2db64-0385-11e5-91fc-3d807a7ec5a7.png)

**Comment by Evan13698** [comment] 2015-05-26 07:01
Do u have the gmail app?

**Comment by MightyPork** [comment] 2015-05-26 07:02
I'm telling you, github removes it. Send it directly to ondra@ondrovo.com

**Comment by Evan13698** [comment] 2015-05-26 07:03
But why can’t you view this email on gmail so it doesn’t get removed

**Comment by MightyPork** [comment] 2015-05-26 07:06
I *have* viewed it on gmail, for fucks sake. You have to send it directly,
not as a reply.

**Comment by Jiggy-12321** [comment] 2015-05-26 20:29
omg

**Comment by MightyPork** [comment] 2015-05-26 20:34
N.B. I still have not received the file. I vote to close this issue

**Comment by Evan13698** [comment] 2015-05-26 21:43
Ok ok sry. I just have no idea what to do!

**Comment by Evan13698** [comment] 2015-05-26 21:45
Just tell me where to send it to!

**Comment by Evan13698** [comment] 2015-05-26 21:51
Just tell me where to send it so I can keep working on my texture pack!
THATS ALL I WANT!

**Comment by Jiggy-12321** [comment] 2015-05-26 22:01
This seems just like you messed up somewhere. It requires DELIBERATE mistakes to fins this. Restart your project. That seems to be the only solution at this point. I'll wait for @MightyPork to have final say on this, but I say we close this.

**Comment by MightyPork** [comment] 2015-05-26 22:28
@Evan13698 Where to send it? -> https://github.com/MightyPork/rpw/issues/38#issuecomment-105420090
You have to send it in a NEW MAIL, not a reply to what you get from github.

**Comment by MightyPork** [comment] 2015-05-26 22:30
I don't wanna sound rude, so sorry if it came out that way, and I'm sure neither did Jiggy, but come on. If there's something to debug / fix / investigate, we *need* to reproduce it.

**Comment by Jiggy-12321** [comment] 2015-05-26 22:36
I don't mean to be rude, I really don't, but a bug without duplication is like a car crash with no explanation.

**Comment by Evan13698** [comment] 2015-05-27 05:42
Ok look, sry if I got angry and i am sorry if u r getting frustrated, but pls just tell me where to send it, you put in the audio and you close the case. Could you please just do that? Thanks again for helping me...

**Comment by Evan13698** [comment] 2015-05-27 05:45
I thought that you did reproduce it though.. And you said it requires deliberate mistakes to be made which I didn't do... Ok so I will send it to your email...

**Comment by Evan13698** [comment] 2015-05-27 05:48
:-) I have sent it to ondra@ondrovo.com/ mightyporks email. This should work and then we can close this issue :-)

**Comment by MightyPork** [comment] 2015-05-27 09:53
I've put the received ogg file into a project, exported and verified that it works flawlessly. Closing as Cannot Reproduce.

**Closed by MightyPork** 2015-05-27 09:53 UTC
Labels: cannot reproduce, invalid
